name: Commit to Notion
on:
  - push
  - pull_request:
    types: [opened, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit to Notion
        uses: jlcaraballo/gh-notion@0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          NOTION_DATABASE: ${{ secrets.NOTION_DATABASE }}
